# Generator and Discriminator Initialization
WIDTH_PER_STAGE_G = [3 * x // 4 for x in [1024, 1024, 1024, 1024]]
BLOCKS_PER_STAGE_G = [2 * x for x in [1, 1, 1, 1]]
CARDINALITY_PER_STAGE_G = [3 * x for x in [32, 32, 32, 32]]
NOISE_DIMENSION_G = 64

WIDTH_PER_STAGE_D = [*reversed(WIDTH_PER_STAGE_G)]
CARDINALITY_PER_STAGE_D = [*reversed(CARDINALITY_PER_STAGE_G)]
BLOCKS_PER_STAGE_D = [*reversed(BLOCKS_PER_STAGE_G)]

EXPANSION_FACTOR = 2
CONDITION_DIM = 10 # number of class

CONDITION_EMBEDDING_DIM_G = NOISE_DIMENSION_G
CONDITION_EMBEDDING_DIM_D = WIDTH_PER_STAGE_G[0]

# Training Hyperparameters
NUM_EPOCHS = 1000
BATCH_SIZE = 4
LR_G = 1e-8
LR_D = 1e-8

BETA_1 = 0
BETA_2 = 0